/* 蜜语 · 挑战模式关卡脚本与文案库 */

const CHALLENGE_META = {
  speed: {
    label: "极速", icon: "⏱", rounds: 12, timer: 45, noSkip: false,
    intensity: "hot",
    desc: "12 关 · 每关 45 秒限时 · 快节奏冲刺",
    tip: "适合想快速升温、不想拖泥带水的一对",
    intro: "极速挑战开始。倒计时一响就必须动，磨蹭的人会落在后面。",
    outro: "在限时里完成这么多关，你们的默契和体力都很惊人。",
  },
  hardcore: {
    label: "硬核", icon: "💀", rounds: 15, timer: 0, noSkip: true,
    intensity: "deep",
    desc: "15 关 · 禁止跳过 · 强度深入",
    tip: "没有退路，抽到什么就做什么",
    intro: "硬核模式：不许跳过，不许讨价还价。准备好了再点开始。",
    outro: "全程零跳过——这份狠劲和信任，比任何情话都性感。",
  },
  marathon: {
    label: "马拉松", icon: "🏃", rounds: 20, timer: 0, noSkip: false,
    intensity: "hot",
    desc: "20 关 · 耐力考验 · 混合玩法",
    tip: "像长跑一样，前半段留力，后半段才见真章",
    intro: "马拉松挑战：二十关连战，中途想停可以跳过，但别轻易认输。",
    outro: "二十关打完还在彼此身边，今晚可以睡得很沉了。",
  },
  sensory: {
    label: "感官", icon: "👁", rounds: 14, timer: 0, noSkip: false,
    intensity: "warm",
    desc: "14 关 · 蒙眼/慢触/边缘 · 偏前戏",
    tip: "把视觉关掉，其他感觉会放大十倍",
    intro: "感官挑战：慢一点，细一点，感受比速度重要。",
    outro: "你们把彼此的身体摸透了，这种熟悉感会上瘾。",
  },
  roulette: {
    label: "轮盘狂", icon: "🎡", rounds: 16, timer: 0, noSkip: false,
    intensity: "hot",
    desc: "16 关 · 轮盘与骰子为主 · 命运说了算",
    tip: "运气也是情趣的一部分",
    intro: "轮盘狂：命运替你们做决定，转到什么就玩什么。",
    outro: "把身体交给轮盘还能玩到最后，你们胆子真不小。",
  },
  edge: {
    label: "边缘", icon: "🌊", rounds: 12, timer: 60, noSkip: true,
    intensity: "hot",
    desc: "12 关 · 边缘控制 · 不许提前释放",
    tip: "快到顶时停下，重复几次再一起放",
    intro: "边缘挑战：忍住别高潮，谁先失控谁下一轮全程服侍。",
    outro: "能把边缘玩成艺术，你们已经是老手了。",
  },
  sync: {
    label: "同步", icon: "🔗", rounds: 14, timer: 0, noSkip: false,
    intensity: "hot",
    desc: "14 关 · 双人同步关为主 · 一起才算数",
    tip: "一个人爽不算，要两个人一起才有分",
    intro: "同步挑战：今晚没有「我一个人来」，每件事都要一起完成。",
    outro: "连呼吸都同步的人，做别的当然也更合拍。",
  },
  confess: {
    label: "告白", icon: "💬", rounds: 10, timer: 0, noSkip: false,
    intensity: "warm",
    desc: "10 关 · 情境与告白 · 边做边说",
    tip: "嘴上说的和手上做的要一样诚实",
    intro: "告白挑战：边亲热边说实话，害羞可以，撒谎不行。",
    outro: "愿意边做边告白的人，关系已经不只是肉体了。",
  },
  dice: {
    label: "骰子王", icon: "🎲", rounds: 15, timer: 0, noSkip: false,
    intensity: "hot",
    desc: "15 关 · 几乎全是骰子 · 随机组合",
    tip: "部位加动作，每次都不同",
    intro: "骰子王：点数决定部位，动作决定玩法，别指望会重复。",
    outro: "十五次掷骰子都没玩腻，你们组合感太强了。",
  },
  blitz: {
    label: "闪击", icon: "⚡", rounds: 10, timer: 30, noSkip: true,
    intensity: "deep",
    desc: "10 关 · 30 秒极限 · 禁止跳过",
    tip: "最短最狠，适合已经热身完毕的时候",
    intro: "闪击挑战：每关只有三十秒，做不到也要做。",
    outro: "三十秒一关还能扛下来，体能和欲望都是顶配。",
  },
};

const CHALLENGE_DARES = [
  "三十秒内让{other}必须出声，做不到你脱一件。",
  "蒙眼让{other}牵着你走，摸到什么亲什么，坚持两分钟。",
  "用三种速度亲吻{other}腿间（隔着或直接接触），由{other}打分。",
  "边做边说出{other}三个让你发疯的身体细节。",
  "让{other}说「停」才能停，挑战三分钟，看谁先忍不住改口。",
  "互换内衣/袜子（或一件贴身衣物），穿着完成下一关。",
  "只用舌头，不用手指，服侍{other}到腿软。",
  "面对面坐着，手伸进对方裤腰，同时动，节奏必须一致。",
  "选一首歌的长度，在这个时间里不许停手。",
  "让{other}在纸上写敏感部位，你闭眼舔到对应位置。",
  "后入时回头吻{other}，维持十秒，塌腰算失败要重来。",
  "边缘三轮：每轮把{other}弄到快高潮再停，第四轮一起放。",
  "用冰/热交替刺激{other}同一部位，描述{other}每次反应。",
  "命令{other}不许动，你弄三十秒，看{other}忍不忍得住。",
  "模仿{other}平时高潮时的表情给对方看，然后扑上去。",
];

const DAILY_BRIEFS = [
  "今日第一关：慢一点，把气氛铺好。",
  "别急着进入正题，前戏也是正餐。",
  "听对方的呼吸，比听任何指令都重要。",
  "这一关试试反着来——平时主动的躺好。",
  "限时快到了？那就更要专注。",
  "今日宜大胆，不宜害羞。",
  "做的时候看着对方的眼睛。",
  "这一关完成得好，晚上有加餐。",
  "用你最喜欢的方式服侍 TA 一分钟。",
  "不许说话，只用身体回答「想要」。",
  "今日关键词：缠绵，动作放慢一倍。",
  "最后一关，把没做完的补回来。",
];

const CHALLENGE_SCRIPTS = {
  speed: [
    { mode: "cards", tag: "热身", brief: "先热起来，限时四十五秒。", text: "解开{other}最外层衣物，每解开一处亲一下，限时完成。", type: "serve", timer: 45 },
    { mode: "dice", tag: "快掷", brief: "骰子停之前想好怎么做。", timer: 45 },
    { mode: "cards", tag: "口舌", brief: "嘴要比手快。", text: "四十五秒内用嘴唇从{other}脖颈舔到胸口，不许停。", type: "serve", timer: 45 },
    { mode: "wheel", tag: "命运", brief: "轮盘转完立刻执行，别拖。", timer: 45 },
    { mode: "mystery", tag: "盲选", brief: "三选一，选中就做完。", timer: 45 },
    { mode: "cards", tag: "同步", brief: "两个人一起动才算数。", text: "面对面抱紧，下身相贴磨蹭四十五秒，不许进入。", type: "sync", timer: 45, syncBias: true },
    { mode: "dice", tag: "敏感", brief: "掷到敏感部位就重点照顾。", timer: 45 },
    { mode: "scenario", tag: "挑战", brief: "抽到的挑战必须执行。", scenarioKind: "dare", timer: 45 },
    { mode: "cards", tag: "深入", brief: "时间不多，直奔主题。", text: "手指或口舌任选，四十五秒内让{other}明显颤抖。", type: "serve", timer: 45 },
    { mode: "wheel", tag: "加码", brief: "轮盘给你加码了。", timer: 45 },
    { mode: "cards", tag: "互换", brief: "换边，刚才享受的现在服侍。", text: "躺下享受{other}的服务，限时四十五秒，不许指挥。", type: "receive", timer: 45 },
    { mode: "cards", tag: "终冲", brief: "最后一关，把劲使完。", text: "用你们此刻最想的方式互相弄到出声，限时四十五秒。", type: "sync", timer: 45 },
  ],
  hardcore: [
    { mode: "cards", tag: "服从", brief: "硬核第一条：不许跳过。", text: "跪下吻{other}从脚踝到大腿内侧，完整做一遍。", type: "serve" },
    { mode: "mystery", tag: "盲选", brief: "选错了也要做，没有反悔。" },
    { mode: "cards", tag: "深吻", brief: "吻到对方缺氧才算过关。", text: "掐着{other}的腰深吻两分钟，舌头不许离开。", type: "sync" },
    { mode: "dice", tag: "骰罚", brief: "骰子抽到什么就做什么，没有商量。" },
    { mode: "cards", tag: "口舌", brief: "用嘴，不许偷懒。", text: "口舌侍奉{other}直到{other}求停或抓你头发，不许提前停。", type: "serve" },
    { mode: "scenario", tag: "坦白", brief: "边做边说真话。", scenarioKind: "confess" },
    { mode: "wheel", tag: "命运", brief: "轮盘不会怜悯你。" },
    { mode: "cards", tag: "进入", brief: "这一关可以进入了。", text: "缓慢进入{other}，进去后停五秒再动，找到最深的角度。", type: "serve" },
    { mode: "cards", tag: "承受", brief: "躺着接受，不许反攻。", text: "趴好，让{other}从后面进入，你只管配合节奏。", type: "receive" },
    { mode: "dice", tag: "体位", brief: "骰子决定体位，照做。" },
    { mode: "scenario", tag: "极限", brief: "挑战型任务，完成才准下一关。", scenarioKind: "dare" },
    { mode: "cards", tag: "骑乘", brief: "自己动到腿软。", text: "骑在{other}身上自己动，不许停，直到腿酸。", type: "receive" },
    { mode: "mystery", tag: "终选", brief: "三选一，选最狠的那张。" },
    { mode: "cards", tag: "同步", brief: "两人必须同时高潮才算。", text: "用你们最爽的体位做到两人一起高潮，做完相拥不许立刻分开。", type: "sync" },
    { mode: "cards", tag: "终章", brief: "最后一关，倾尽全力。", text: "后入深顶{other}，每一下都顶实，维持到两人都筋疲力尽。", type: "serve" },
  ],
  marathon: [
    { mode: "cards", tag: "序章", brief: "马拉松第一公里，慢起步。", text: "从背后抱住{other}，手伸进衣服里摸五分钟，不许进裤。", type: "serve" },
    { mode: "dice", tag: "骰子", brief: "随机部位，慢慢探索。" },
    { mode: "wheel", tag: "轮盘", brief: "命运第一次介入。" },
    { mode: "cards", tag: "脱衣", brief: "一件一件来，别急。", text: "帮{other}脱到只剩内衣，每脱一件吻一处。", type: "serve" },
    { mode: "mystery", tag: "盲选", brief: "盲选一张，温柔执行。" },
    { mode: "scenario", tag: "情境", brief: "进入角色，演下去。", scenarioKind: "roleplay" },
    { mode: "cards", tag: "前戏", brief: "前戏也是正经事。", text: "用嘴唇和手指把{other}弄湿/硬，不许进入。", type: "serve" },
    { mode: "dice", tag: "再掷", brief: "第二次骰子，加码。" },
    { mode: "cards", tag: "互换", brief: "换边，公平起见。", text: "换{other}来服侍你，享受三分钟不许催。", type: "receive" },
    { mode: "wheel", tag: "二转", brief: "轮盘第二次，可能更狠。" },
    { mode: "scenario", tag: "悄悄话", brief: "边摸边说。", scenarioKind: "whisper" },
    { mode: "cards", tag: "同步", brief: "一起动，节奏要合。", text: "互相手淫，看着对方表情，同步加快或放慢。", type: "sync", syncBias: true },
    { mode: "mystery", tag: "盲选II", brief: "再盲选一次。" },
    { mode: "cards", tag: "口舌", brief: "口舌伺候，耐心一点。", text: "用嘴让{other}舒服，至少三分钟，不许敷衍。", type: "serve" },
    { mode: "dice", tag: "体位", brief: "骰子决定怎么进入。" },
    { mode: "cards", tag: "深入", brief: "马拉松过半，可以深了。", text: "选你们喜欢的体位进入，维持五分钟以上。", type: "sync" },
    { mode: "scenario", tag: "挑战", brief: "抽挑战，做完才走。", scenarioKind: "dare" },
    { mode: "wheel", tag: "三转", brief: "第三轮盘，撑住。" },
    { mode: "cards", tag: "骑乘", brief: "换骑乘，换角度。", text: "骑乘{other}或让{other}骑你，自己控制深浅两分钟。", type: "sync" },
    { mode: "cards", tag: "终章", brief: "最后一关，跑到终点。", text: "做到两人一起高潮，然后相拥休息，今晚到此为止——或继续。", type: "sync" },
  ],
  sensory: [
    { mode: "scenario", tag: "蒙眼", brief: "蒙上眼睛，触觉放大。", scenarioKind: "roleplay", text: "【蒙眼触摸】{other}蒙眼，你只能用指尖从额头滑到小腹，猜哪里让{other}抖了。" },
    { mode: "cards", tag: "慢吻", brief: "慢，再慢一点。", text: "用嘴唇磨蹭{other}颈侧，一次蹭三十秒，换边再来。", type: "serve" },
    { mode: "dice", tag: "轻触", brief: "掷到部位只用指尖。", text: "只用指尖" },
    { mode: "cards", tag: "呵气", brief: "气息也是武器。", text: "对着{other}耳后和锁骨呵气，然后轻咬，反复五分钟。", type: "serve" },
    { mode: "scenario", tag: "悄悄话", brief: "边说边摸。", scenarioKind: "whisper" },
    { mode: "cards", tag: "隔衣", brief: "隔着布料更磨人。", text: "隔着内裤用手掌按压{other}最敏感处，不许伸进去，磨到{other}求。", type: "serve" },
    { mode: "mystery", tag: "盲选", brief: "看不见更刺激。" },
    { mode: "cards", tag: "边缘", brief: "快到顶时停下。", text: "把{other}弄到快高潮，然后停手三十秒，重复两次。", type: "serve" },
    { mode: "wheel", tag: "感官", brief: "轮盘决定感官玩法。" },
    { mode: "scenario", tag: "告白", brief: "说出真实感受。", scenarioKind: "confess" },
    { mode: "cards", tag: "舔舐", brief: "舌头要慢。", text: "从{other}胸口一路舔到肚脐，再往下，越慢越好。", type: "serve" },
    { mode: "cards", tag: "同步", brief: "两人同时摸，不许进。", text: "互相隔衣抚摸，感受硬度/湿度，不许脱光。", type: "sync" },
    { mode: "dice", tag: "再掷", brief: "再掷一次，轻一点。" },
    { mode: "cards", tag: "终感", brief: "最后一关，感官收尾。", text: "关灯，在黑暗里只用嘴唇找到{other}最敏感处，照顾三分钟。", type: "serve" },
  ],
  roulette: [
    { mode: "wheel", tag: "开局", brief: "第一转，命运开场。" },
    { mode: "wheel", tag: "二转", brief: "再转，别抱怨。" },
    { mode: "dice", tag: "骰补", brief: "轮盘不够骰子来凑。" },
    { mode: "wheel", tag: "三转", brief: "第三轮盘。" },
    { mode: "mystery", tag: "盲选", brief: "偶尔换口味。" },
    { mode: "wheel", tag: "四转", brief: "第四转，加码。" },
    { mode: "wheel", tag: "五转", brief: "轮盘狂中段。" },
    { mode: "dice", tag: "骰子", brief: "掷部位加动作。" },
    { mode: "wheel", tag: "六转", brief: "继续转。" },
    { mode: "scenario", tag: "挑战", brief: "轮盘累了做挑战。", scenarioKind: "dare" },
    { mode: "wheel", tag: "七转", brief: "后半场开始。" },
    { mode: "wheel", tag: "八转", brief: "转到什么做什么。" },
    { mode: "wheel", tag: "九转", brief: "别停。" },
    { mode: "dice", tag: "终骰", brief: "骰子收尾。" },
    { mode: "wheel", tag: "终转", brief: "最后一转，听天由命。" },
    { mode: "wheel", tag: "加赛", brief: "加赛一转，惊喜或惊吓。" },
  ],
  edge: [
    { mode: "cards", tag: "预热", brief: "先暖场，别急着放。", text: "亲吻抚摸{other}全身，不许碰最敏感处，持续三分钟。", type: "serve", timer: 60 },
    { mode: "cards", tag: "边缘1", brief: "第一次边缘，忍住。", text: "口舌或手指把{other}弄到快高潮，立刻停三十秒。", type: "serve", timer: 60 },
    { mode: "cards", tag: "边缘2", brief: "第二次，更难忍。", text: "再来一次边缘，这次停的时候亲吻{other}安抚。", type: "serve", timer: 60 },
    { mode: "scenario", tag: "忍耐", brief: "描述你有多想继续。", scenarioKind: "whisper", timer: 60 },
    { mode: "cards", tag: "互换", brief: "换边接受边缘。", text: "换{other}对你做边缘控制，你不许自己动。", type: "receive", timer: 60 },
    { mode: "cards", tag: "边缘3", brief: "第三次边缘。", text: "互相弄到快高潮，同时停手，牵手深呼吸。", type: "sync", timer: 60 },
    { mode: "dice", tag: "骰子", brief: "骰子决定怎么磨。", timer: 60 },
    { mode: "cards", tag: "禁止", brief: "这一分钟不许高潮。", text: "维持刺激但降低强度，熬满一分钟不许释放。", type: "sync", timer: 60 },
    { mode: "scenario", tag: "挑战", brief: "挑战你的自制力。", scenarioKind: "dare", timer: 60 },
    { mode: "cards", tag: "边缘4", brief: "第四次边缘，最残忍。", text: "把{other}弄到求你别停，然后真的停三十秒。", type: "serve", timer: 60 },
    { mode: "cards", tag: "同步边", brief: "两人同时边缘。", text: "互相刺激到濒临高潮，约定同时停，重复两次。", type: "sync", timer: 60 },
    { mode: "cards", tag: "释放", brief: "最后一关，可以放了。", text: "倒数三二一后一起放到高潮，不许提前。", type: "sync", timer: 90 },
  ],
  sync: [
    { mode: "cards", tag: "牵手", brief: "同步从牵手开始。", text: "十指相扣，接吻同时手伸进对方衣服，节奏一致。", type: "sync", syncBias: true },
    { mode: "cards", tag: "磨蹭", brief: "下身同步磨蹭。", text: "面对面站着，下身紧贴前后磨蹭，磨到两人都喘。", type: "sync", syncBias: true },
    { mode: "scenario", tag: "情境", brief: "演一段双人剧情。", scenarioKind: "roleplay" },
    { mode: "cards", tag: "互摸", brief: "同时摸，同时忍。", text: "互相把手伸进内裤，同时抚摸，保持同频。", type: "sync", syncBias: true },
    { mode: "mystery", tag: "盲选", brief: "选一起完成的牌。", syncBias: true },
    { mode: "cards", tag: "轮流", brief: "三十秒换边。", text: "轮流口舌服侍三十秒，用计时器，无缝衔接。", type: "sync", syncBias: true },
    { mode: "wheel", tag: "轮盘", brief: "轮盘抽到同步就一起做。", syncBias: true },
    { mode: "cards", tag: "对视", brief: "看着对方做。", text: "全裸相对坐着，互相手淫，必须对视，不许闭眼。", type: "sync", syncBias: true },
    { mode: "scenario", tag: "告白", brief: "同步告白。", scenarioKind: "confess" },
    { mode: "cards", tag: "呼吸", brief: "呼吸同步。", text: "额头贴额头，同步呼吸，下身相贴慢慢摇腰。", type: "sync", syncBias: true },
    { mode: "dice", tag: "骰子", brief: "掷到后两人一起执行。", syncBias: true },
    { mode: "cards", tag: "边缘", brief: "一起到边缘再停。", text: "互相弄到快高潮，同时停，再同时继续。", type: "sync", syncBias: true },
    { mode: "scenario", tag: "挑战", brief: "双人挑战。", scenarioKind: "dare" },
    { mode: "cards", tag: "终同步", brief: "最后一关，完全同步。", text: "用你们最合拍的方式做到两人一起高潮，时间不限。", type: "sync", syncBias: true },
  ],
  confess: [
    { mode: "scenario", tag: "坦白", brief: "先说一个秘密。", scenarioKind: "confess" },
    { mode: "cards", tag: "边吻边说", brief: "吻一下说一句。", text: "每亲{other}一处，说一句你喜欢{other}那里的理由。", type: "serve" },
    { mode: "scenario", tag: "幻想", brief: "说出小幻想。", scenarioKind: "confess" },
    { mode: "cards", tag: "边摸边说", brief: "摸着坦白。", text: "抚摸{other}时描述你现在的感受，不许停手。", type: "serve" },
    { mode: "scenario", tag: "情境", brief: "角色扮演里告白。", scenarioKind: "roleplay" },
    { mode: "scenario", tag: "悄悄话", brief: "耳边说实话。", scenarioKind: "whisper" },
    { mode: "cards", tag: "渴望", brief: "说出渴望。", text: "告诉{other}你今晚最想被怎么对待，然后{other}照做一分钟。", type: "receive" },
    { mode: "scenario", tag: "挑战", brief: "挑战里带告白。", scenarioKind: "dare" },
    { mode: "cards", tag: "回忆", brief: "回忆第一次。", text: "边亲热边复述你们第一次心动的瞬间。", type: "sync" },
    { mode: "scenario", tag: "终白", brief: "最后一关，最真心的话。", scenarioKind: "confess" },
  ],
  dice: [
    { mode: "dice", tag: "1", brief: "第一次掷骰，热身。" },
    { mode: "dice", tag: "2", brief: "掷到敏感带就重点照顾。" },
    { mode: "dice", tag: "3", brief: "换边，再掷。" },
    { mode: "dice", tag: "4", brief: "动作加码。" },
    { mode: "dice", tag: "5", brief: "部位和动作要配合。" },
    { mode: "dice", tag: "6", brief: "中段休息？不，继续掷。" },
    { mode: "dice", tag: "7", brief: "掷到深入动作就执行。" },
    { mode: "dice", tag: "8", brief: "双人骰：两人各掷一次。" },
    { mode: "dice", tag: "9", brief: "重复组合就换方式做。" },
    { mode: "dice", tag: "10", brief: "第十掷，别手软。" },
    { mode: "dice", tag: "11", brief: "部位优先腿间。" },
    { mode: "dice", tag: "12", brief: "动作优先口舌。" },
    { mode: "dice", tag: "13", brief: "快掷，限时执行。" },
    { mode: "dice", tag: "14", brief: "倒数第二掷。" },
    { mode: "dice", tag: "15", brief: "终掷，做完收工。" },
  ],
  blitz: [
    { mode: "cards", tag: "1", brief: "三十秒脱一件。", text: "三十秒内脱掉{other}一件衣服并亲新露出的皮肤。", type: "serve", timer: 30 },
    { mode: "cards", tag: "2", brief: "三十秒深吻。", text: "三十秒舌吻{other}，手同时伸进裤腰。", type: "sync", timer: 30 },
    { mode: "dice", tag: "3", brief: "掷完立刻做，三十秒。", timer: 30 },
    { mode: "cards", tag: "4", brief: "三十秒口舌。", text: "三十秒口舌刺激{other}最敏感处。", type: "serve", timer: 30 },
    { mode: "wheel", tag: "5", brief: "轮盘定生死，三十秒执行。", timer: 30 },
    { mode: "cards", tag: "6", brief: "三十秒互摸。", text: "三十秒互相隔衣摸腿根，看谁先喘。", type: "sync", timer: 30 },
    { mode: "scenario", tag: "7", brief: "三十秒挑战。", scenarioKind: "dare", timer: 30 },
    { mode: "cards", tag: "8", brief: "三十秒进入或紧贴。", text: "三十秒内进入{other}或紧贴磨蹭到最深。", type: "serve", timer: 30 },
    { mode: "mystery", tag: "9", brief: "盲选，三十秒做完。", timer: 30 },
    { mode: "cards", tag: "10", brief: "终关三十秒冲刺。", text: "三十秒全力顶弄或摩擦，怎么爽怎么来。", type: "sync", timer: 30 },
  ],
};

function buildChallengeRounds(id) {
  const meta = CHALLENGE_META[id];
  const script = CHALLENGE_SCRIPTS[id]?.slice() || [];
  if (!meta) return [];
  const rounds = [];
  for (let i = 0; i < meta.rounds; i++) {
    const base = script[i % script.length] || { mode: "cards", tag: `第 ${i + 1} 关`, brief: "完成本关。" };
    rounds.push({ ...base, tag: base.tag.includes(String(i + 1)) ? base.tag : `${base.tag} ·${i + 1}` });
  }
  return rounds;
}

(function initChallenges() {
  Object.entries(CHALLENGE_META).forEach(([id, meta]) => {
    CHALLENGE_PRESETS[id] = { ...CHALLENGE_PRESETS[id], ...meta };
  });

  DAILY_MODIFIERS.push(
    { id: "marathon_lite", name: "迷你马拉松", desc: "今日 12 关连战，不许偷懒", rounds: 12 },
    { id: "edge_day", name: "边缘之日", desc: "今日每关做边缘控制", edgeBias: true },
    { id: "confess_day", name: "告白之日", desc: "今日多说真心话", scenarioBias: true, scenarioKind: "confess" },
    { id: "blitz_day", name: "闪击之日", desc: "今日每关限时 30 秒", timer: 30 },
    { id: "hard_day", name: "硬核一日", desc: "今日禁止跳过", noSkip: true },
    { id: "dice_day", name: "骰子之日", desc: "今日以骰子为主", modeLock: "dice" },
    { id: "wheel_day", name: "轮盘之日", desc: "今日以轮盘为主", modeLock: "wheel" },
  );
})();