/* 蜜语 · 扩展场景包（厕所/汽车/飞机/教室…） */

Object.assign(SCENE_CATALOG, {
  restroom: {
    id: "restroom",
    name: "厕所隔间",
    icon: "🚻",
    tagline: "门外有人，门内只有你俩",
    category: "public",
    desc: "商场或酒吧的洗手间。隔间狭促，锁扣一扣，外面脚步声反而成了催情剂。",
    color: "#8ecae6",
    stages: [
      {
        name: "洗手台",
        intensity: "warm",
        intro: "镜前补妆/整理，{other}从背后贴近。门外人来人往，你们压低声音。",
        rounds: [
          { kind: "roleplay", text: "【洗手台】{self}帮{other}整理衣领，手指故意蹭过喉结/锁骨。镜子里对视，像不认识的人那样搭讪。" },
          { kind: "dare", text: "隔间门外有人洗手——你们在镜前深吻十秒，听见水声才分开。" },
          { kind: "whisper", text: "贴着{other}耳朵：「要是现在进隔间，你第一件想做的事是什么？」" },
          { kind: "confess", text: "承认你有没有在公共场所洗手间想过{other}。" },
        ],
      },
      {
        name: "隔间",
        intensity: "hot",
        intro: "锁扣咔哒。空间只够贴身。呼吸声被瓷砖放大。",
        rounds: [
          { kind: "roleplay", text: "【隔间】{other}坐马桶盖，你跪在两腿间——外面脚步声经过时动作要轻、要慢。" },
          { kind: "dare", text: "咬住{other}嘴唇不许出声，手伸进裤腰弄湿/弄硬，有人敲门就停三秒再继续。" },
          { kind: "whisper", text: "用气音描述：隔间这么窄，{other}的身体把你压得多紧。" },
          { kind: "dare", text: "让{other}捂嘴，你口舌伺候到{other}腿抖——忍住不叫。" },
        ],
      },
      {
        name: "镜雾",
        intensity: "hot",
        intro: "隔间里也有镜子。热气、雾气、狭窄。",
        rounds: [
          { kind: "roleplay", text: "【镜雾】用手指在镜上写「想要」，拉{other}转身从后抱住，镜子里看{other}表情。" },
          { kind: "dare", text: "手指进入{other}，每有人走过门外就停，脚步远去再继续。" },
          { kind: "whisper", text: "告诉{other}：这种偷来的安静，让你比平时更硬/更湿。" },
          { kind: "roleplay", text: "【冒险】开门缝看一眼无人，把{other}拉回来抵在门上亲——像差点被发现。" },
        ],
      },
      {
        name: "洗手离开",
        intensity: "deep",
        intro: "整理衣服，像什么都没发生。但眼神出卖一切。",
        rounds: [
          { kind: "dare", text: "隔间内站立后入或面对面抬腿，快速深顶二十下，然后立刻整理衣冠出去。" },
          { kind: "roleplay", text: "【洗手离开】并排在洗手台洗手，膝盖故意碰一下，像陌生人。" },
          { kind: "confess", text: "说出你还想和{other}在哪类「不该做的地方」再来一次。" },
          { kind: "whisper", text: "出门前在{other}耳边约定：回家路上不许说话，到家继续。" },
        ],
      },
    ],
  },

  car_parked: {
    id: "car_parked",
    name: "车内深夜",
    icon: "🚗",
    tagline: "后座狭窄，车窗起雾",
    category: "vehicle",
    desc: "车停在人少的路边或地下车库。引擎凉了，体温在升高。",
    color: "#5c6b73",
    stages: [
      {
        name: "驾驶座",
        intensity: "warm",
        intro: "停车。手刹拉起。电台低响。",
        rounds: [
          { kind: "roleplay", text: "【驾驶座】{self}手还搭方向盘，{other}俯身过来吻，挡位杆碍事——拨到P。" },
          { kind: "dare", text: "在驾驶座互相隔衣摸五分钟，车窗故意不起雾。" },
          { kind: "whisper", text: "说{other}坐在你旁边时，你最想把手放在哪。" },
          { kind: "confess", text: "坦白你有没有在车里单独想过{other}。" },
        ],
      },
      {
        name: "后座",
        intensity: "hot",
        intro: "爬到后座。空间局促反而更亲密。",
        rounds: [
          { kind: "roleplay", text: "【后座】{other}躺，你俯身，头顶撞到车顶也不停——低矮空间里的压迫感。" },
          { kind: "dare", text: "脱到只剩内衣/内裤，在后座互相口舌伺候，车窗外有人经过就停。" },
          { kind: "whisper", text: "描述后座皮革味混着{other}体香。" },
          { kind: "dare", text: "让{other}趴窗，雾glass上呵气写字，你从后亲颈到腰。" },
        ],
      },
      {
        name: "起雾",
        intensity: "hot",
        intro: "玻璃蒙上一层白雾。外面世界变模糊。",
        rounds: [
          { kind: "roleplay", text: "【起雾】用手指在侧窗画心，然后拉{other}坐你腿上，对着雾面做——外面看不见里面。" },
          { kind: "dare", text: "手指或口舌把{other}弄到出声，立刻捂嘴，笑场也要继续。" },
          { kind: "whisper", text: "边弄边说：「这车窗起雾，都是因为我们。」" },
          { kind: "roleplay", text: "【警报】假装远处有手电光——紧张三秒，发现安全，更猛烈地吻下去。" },
        ],
      },
      {
        name: "归途",
        intensity: "deep",
        intro: "必须回家或继续开。最后一轮在后座解决。",
        rounds: [
          { kind: "dare", text: "后座狭窄体位进入或紧贴磨蹭，车震一下就当节拍。" },
          { kind: "roleplay", text: "【归途】整理衣服坐回前排，手却在副驾底下仍握着{other}大腿。" },
          { kind: "confess", text: "说出下次想把车开到哪里再停一次。" },
          { kind: "dare", text: "高潮后相拥在后座休息，听雨打车顶或车库滴水。" },
        ],
      },
    ],
  },

  airplane: {
    id: "airplane",
    name: "万米高空",
    icon: "✈️",
    tagline: "毯子之下，云端之上",
    category: "vehicle",
    desc: "红眼航班或头等舱。机舱昏暗，引擎轰鸣像白噪音。",
    color: "#4a6fa5",
    stages: [
      {
        name: "登机",
        intensity: "warm",
        intro: "邻座就是{other}。安全带灯还亮着。",
        rounds: [
          { kind: "roleplay", text: "【登机】{self}是邻座陌生人搭讪：「也是一个人？」十句以内要到了{other}的手。" },
          { kind: "dare", text: "安全带灯亮时，手在毯子下握住{other}手指，一根根舔或吻。" },
          { kind: "whisper", text: "在引擎声里贴耳说：「落地前，我想对{other}做一件事。」" },
          { kind: "confess", text: "说一个你在交通工具上幻想过{other}的场景。" },
        ],
      },
      {
        name: "毯子",
        intensity: "hot",
        intro: "空乘发毯。盖住腿。盖住手。盖不住心跳。",
        rounds: [
          { kind: "roleplay", text: "【毯子】共用一条毯，手在毯下从膝盖摸到大腿根，表情保持看电影。" },
          { kind: "dare", text: "毯子下互相隔裤抚摸到湿/硬，空乘经过立刻停、微笑、继续。" },
          { kind: "whisper", text: "描述毯子下{other}的手在做什么，细节小声说。" },
          { kind: "dare", text: "让{other}咬嘴唇忍呻吟，你手指在里面打圈两分钟。" },
        ],
      },
      {
        name: "卫生间",
        intensity: "hot",
        intro: "机舱后部那个窄小的金属间。排队也要冒险。",
        rounds: [
          { kind: "roleplay", text: "【卫生间】一人先进占住，另一人「借厕所」挤进来——锁上门，空间只够贴在一起。" },
          { kind: "dare", text: "在狭小空间里口舌接吻到喘不过气，手伸进衣服里。" },
          { kind: "whisper", text: "说：「 turbulence 时更要抓紧我」——然后抓紧做。" },
          { kind: "roleplay", text: "【洗脸】开水龙头盖住声音，镜前从后抱住{other}，镜子里飞机颠簸。" },
        ],
      },
      {
        name: "降落",
        intensity: "deep",
        intro: "安全带灯再亮。降落前要把欲望安放或释放。",
        rounds: [
          { kind: "dare", text: "卫生间或最后一排帘后，快速激烈地弄彼此到边缘，灯亮前整理衣冠。" },
          { kind: "roleplay", text: "【降落】耳压变化时吻{other}，像帮对方咽下去——吻完说「欢迎落地」。" },
          { kind: "confess", text: "约定下次旅行：去程放肆还是回程放肆。" },
          { kind: "whisper", text: "计划酒店第一分钟要做什么，列三步。" },
        ],
      },
    ],
  },

  locker_room: {
    id: "locker_room",
    name: "更衣室",
    icon: "🚿",
    tagline: "汗味、塑料凳、帘子后",
    category: "public",
    desc: "体育馆或泳池更衣室。别人刚走，淋浴还在滴水。",
    color: "#90be6d",
    stages: [
      {
        name: "储物柜",
        intensity: "warm",
        intro: "金属柜门一排排。只有你们拖鞋声。",
        rounds: [
          { kind: "roleplay", text: "【储物柜】{other}换衣，你从背后递毛巾，毛巾擦过{other}后背停太久。" },
          { kind: "dare", text: "互换一件运动内衣/短裤穿上，穿着亲一下。" },
          { kind: "whisper", text: "说{other}运动后哪一处汗湿的样子最性感。" },
          { kind: "confess", text: "承认你有没有偷看过{other}换衣服。" },
        ],
      },
      {
        name: "淋浴区",
        intensity: "hot",
        intro: "塑料帘子。水声很大。",
        rounds: [
          { kind: "roleplay", text: "【淋浴区】共用一个喷头，帮{other}冲背——手滑到前面也不收回。" },
          { kind: "dare", text: "跪地口交，水打在你背上，{other}扶墙。" },
          { kind: "whisper", text: "在水声里喊一句骚话，听不清也算。" },
          { kind: "dare", text: "关掉水，在湿滑地板上拥抱磨蹭到两人都硬/湿。" },
        ],
      },
      {
        name: "长凳",
        intensity: "hot",
        intro: "更衣长凳。毛巾铺着。镜子里两个人赤裸。",
        rounds: [
          { kind: "roleplay", text: "【长凳】{other}坐长凳腿分开，你跪中间口舌伺候，镜子里看{other}仰头。" },
          { kind: "dare", text: "让{other}手撑长凳翘臀，你从后舔或手指，维持两分钟。" },
          { kind: "whisper", text: "描述更衣室镜子里的{other}让你多想要。" },
          { kind: "roleplay", text: "【催促】假装听见外面人声——紧张一秒，发现安全，更激烈。" },
        ],
      },
      {
        name: "离场",
        intensity: "deep",
        intro: "衣服要穿回去。但身体已经不想走。",
        rounds: [
          { kind: "dare", text: "长凳或墙边站立进入，快速深顶，穿好衣服前不许停。" },
          { kind: "roleplay", text: "【离场】只穿好外套，里面真空——牵手出门，捏一下手暗示回家。" },
          { kind: "confess", text: "说出你还想和{other}在哪类更衣室/浴室再来。" },
          { kind: "dare", text: "高潮后真的冲干净穿衣，但回家车上手不许老实。" },
        ],
      },
    ],
  },

  classroom: {
    id: "classroom",
    name: "空教室",
    icon: "📚",
    tagline: "放学后的粉笔与课桌",
    category: "indoor",
    desc: "傍晚教室。窗帘半拉，夕阳把课桌染成金色。扮演师生或旧日同学。",
    color: "#e9c46a",
    stages: [
      {
        name: "补课",
        intensity: "warm",
        intro: "只有你们「补课」。黑板还有公式。",
        rounds: [
          { kind: "roleplay", text: "【补课】{self}是老师，{other}坐第一排。答错题——惩罚是亲一下，位置你指定。" },
          { kind: "dare", text: "在讲台边接吻，窗外有人影立刻分开，人走远再继续。" },
          { kind: "whisper", text: "说{other}穿校服/衬衫时哪一点最让你分心。" },
          { kind: "confess", text: "坦白学生时代的幻想（不必真是师生，可以是同学）。" },
        ],
      },
      {
        name: "课桌",
        intensity: "hot",
        intro: "课桌高度刚好。粉笔灰味道。",
        rounds: [
          { kind: "roleplay", text: "【课桌】{other}坐桌上，你站两腿间，从衬衫下摆摸进去。" },
          { kind: "dare", text: "让{other}趴桌上翘臀，裙子/裤腰拉下，从后亲吻腿根。" },
          { kind: "whisper", text: "描述课桌上{other}趴着时腰线让你多想顶进去。" },
          { kind: "dare", text: "在黑板上写一句色情话，写完转身把{other}按在黑板前。" },
        ],
      },
      {
        name: "讲台",
        intensity: "hot",
        intro: "讲台比课桌更象征「权力」。",
        rounds: [
          { kind: "roleplay", text: "【讲台】{other}跪讲台前，你坐讲台边沿，像批改作业一样摸{other}头控制节奏。" },
          { kind: "dare", text: "口舌伺候到{other}抓讲台边，粉笔盒掉地也不停。" },
          { kind: "whisper", text: "命令{other}说「老师，我还想要」才继续。" },
          { kind: "roleplay", text: "【换角】学生反过来把老师按在讲台——今晚作业是取悦对方。" },
        ],
      },
      {
        name: "放学铃",
        intensity: "deep",
        intro: "远处传来铃声或清洁工脚步声。要结束了——或要加速了。",
        rounds: [
          { kind: "dare", text: "课桌上进入或骑乘，每顶一下讲一个当年暗恋细节。" },
          { kind: "roleplay", text: "【放学铃】匆忙整理衣服书包，牵手跑过走廊，像真的逃课去开房。" },
          { kind: "confess", text: "说出你想和{other}在母校哪间教室再来一次。" },
          { kind: "dare", text: "做到高潮，然后安静坐回座位，对视三秒一起笑。" },
        ],
      },
    ],
  },

  cinema: {
    id: "cinema",
    name: "电影院",
    icon: "🎬",
    tagline: "最后一排，银幕反光",
    category: "public",
    desc: "深夜场次。人稀。爆米花甜，空气里全是黑暗。",
    color: "#9d4edd",
    stages: [
      {
        name: "检票",
        intensity: "warm",
        intro: "检票员撕票。放映厅门关上，光暗下来。",
        rounds: [
          { kind: "roleplay", text: "【检票】牵手进场，在楼梯拐角偷吻，银幕光打在脸上。" },
          { kind: "dare", text: "选最后一排最角落，落座前手伸进{other}后腰。" },
          { kind: "whisper", text: "说今晚电影不重要，{other}才是正片。" },
          { kind: "confess", text: "承认你有没有在电影院想过{other}。" },
        ],
      },
      {
        name: "黑暗",
        intensity: "warm",
        intro: "电影开场。只有脸被银幕照亮一瞬一瞬。",
        rounds: [
          { kind: "roleplay", text: "【黑暗】手在扶手底下摸{other}大腿，指尖往里，{other}夹紧或放松你决定。" },
          { kind: "dare", text: "喂{other}爆米花，手指沾黄油让{other}舔掉。" },
          { kind: "whisper", text: "贴耳描述银幕上哪一幕让你想到{other}身体。" },
          { kind: "dare", text: "在外套掩护下隔衣抚摸到{other}明显反应。" },
        ],
      },
      {
        name: "最后一排",
        intensity: "hot",
        intro: "后排无人。椅背可调节。",
        rounds: [
          { kind: "roleplay", text: "【最后一排】{other}半躺椅背，你俯身吻颈，电影爆炸声盖住喘息。" },
          { kind: "dare", text: "跪在两椅之间口舌伺候，银幕闪光时抬头看{other}表情。" },
          { kind: "whisper", text: "说：「要是全场只有我们，你会叫多大声？」" },
          { kind: "dare", text: "手指进入{other}，节奏跟着电影配乐。" },
        ],
      },
      {
        name: "散场",
        intensity: "deep",
        intro: "灯亮前最后一波高潮，或牵手在人群中装作无事。",
        rounds: [
          { kind: "dare", text: "灯亮前十秒快速弄到边缘，灯亮时坐直擦嘴整理。" },
          { kind: "roleplay", text: "【散场】混在人群里，手在{other}臀上捏一下——只有你们懂。" },
          { kind: "confess", text: "约定下次看恐怖片还是爱情片——哪种更适合在影院动手。" },
          { kind: "whisper", text: "回家车上复述影院里最想对{other}做却没做完的事。" },
        ],
      },
    ],
  },

  library: {
    id: "library",
    name: "图书馆",
    icon: "📖",
    tagline: "禁声区，禁不住心跳",
    category: "public",
    desc: "闭馆前的角落书架。纸味、灰尘、安静得能听见翻页。",
    color: "#6d597a",
    stages: [
      {
        name: "书架",
        intensity: "warm",
        intro: "高书架形成窄巷。外面是自习区。",
        rounds: [
          { kind: "roleplay", text: "【书架】假装找书，身体贴{other}后背，手绕到前面隔衣摸胸/腹。" },
          { kind: "dare", text: "抽一本情色小说念一段，念一句亲一下。" },
          { kind: "whisper", text: "用气音说最骚的话——音量不许超过翻书声。" },
          { kind: "confess", text: "说你在安静场所想过{other}的一次经历。" },
        ],
      },
      {
        name: "阅览桌",
        intensity: "hot",
        intro: "隔板小桌。下半身藏在桌下。",
        rounds: [
          { kind: "roleplay", text: "【阅览桌】面对面坐，桌下脚缠脚，手伸到对方腿间。" },
          { kind: "dare", text: "桌下口舌或手指伺候，上半身假装看书，有人经过就停。" },
          { kind: "whisper", text: "写纸条：「桌下在做什么」——递给{other}看。" },
          { kind: "dare", text: "让{other}咬笔帽忍声，你弄两分钟。" },
        ],
      },
      {
        name: "禁声",
        intensity: "hot",
        intro: "安静是规则。打破规则更刺激。",
        rounds: [
          { kind: "roleplay", text: "【禁声】约定不许出声，谁出声谁被捂嘴多弄一分钟。" },
          { kind: "dare", text: "在书架巷里深吻，书掉地发出声——惩罚是一个更色的动作。" },
          { kind: "whisper", text: "描述{other}忍声时表情多让你想弄哭。" },
          { kind: "roleplay", text: "【管理员】假装管理员咳嗽——分开一秒，人走远继续。" },
        ],
      },
      {
        name: "闭馆",
        intensity: "deep",
        intro: "广播响：闭馆时间。最后一格书架。",
        rounds: [
          { kind: "dare", text: "书架间站立后入，手捂{other}嘴，快射/高潮前停，整理衣冠走出去。" },
          { kind: "roleplay", text: "【闭馆】牵手走出旋转门，像刚考完试的学生——其实刚做完坏事。" },
          { kind: "confess", text: "说出你想和{other}在哪种安静场所再来。" },
          { kind: "whisper", text: "约定回家补完图书馆没做完的事。" },
        ],
      },
    ],
  },

  elevator: {
    id: "elevator",
    name: "电梯",
    icon: "🛗",
    tagline: "楼层数字在跳，心跳也是",
    category: "public",
    desc: "公寓或酒店电梯。镜面墙、监控、楼层一到就停的刺激。",
    color: "#b5838d",
    stages: [
      {
        name: "上行",
        intensity: "warm",
        intro: "门关上。数字从1开始跳。",
        rounds: [
          { kind: "roleplay", text: "【上行】镜面里对视，{self}从背后环住{other}，手在腰上。" },
          { kind: "dare", text: "在下一层到达前深吻，门开就分开，像陌生人。" },
          { kind: "whisper", text: "说：「要是电梯卡住，你第一件事做什么？」" },
          { kind: "confess", text: "承认电梯里想过{other}吗。" },
        ],
      },
      {
        name: "镜面",
        intensity: "hot",
        intro: "三面镜子。无处躲藏。",
        rounds: [
          { kind: "roleplay", text: "【镜面】让{other}面对镜子手撑墙，你从后亲颈，镜子里看{other}眼神。" },
          { kind: "dare", text: "手伸进{other}裤腰，镜子里看自己的手在动。" },
          { kind: "whisper", text: "描述镜中{other}表情。" },
          { kind: "dare", text: "跪下口交，电梯到层前十秒起来整理。" },
        ],
      },
      {
        name: "故障",
        intensity: "hot",
        intro: "假装故障停住。或真按了停层键。",
        rounds: [
          { kind: "roleplay", text: "【故障】按紧急铃停住，「维修」十分钟——其实只有你们，在角落做。" },
          { kind: "dare", text: "限时：未知何时恢复，三分钟弄到{other}腿软。" },
          { kind: "whisper", text: "在密闭空间里说有多想要{other}。" },
          { kind: "roleplay", text: "【恢复】叮一声继续上行，衣衫凌乱，互相整理，忍住笑。" },
        ],
      },
      {
        name: "顶层",
        intensity: "deep",
        intro: "顶层或地下车库。门开，空气不同。",
        rounds: [
          { kind: "dare", text: "电梯到地下车库，在角落快速亲热一分钟再走向车/家。" },
          { kind: "roleplay", text: "【顶层】天台门前吻，风大，手伸进衣服。" },
          { kind: "confess", text: "说出下次想在电梯里做到哪一步。" },
          { kind: "whisper", text: "约定进门第一分钟不许开灯，直接继续。" },
        ],
      },
    ],
  },

  fitting_room: {
    id: "fitting_room",
    name: "试衣间",
    icon: "👗",
    tagline: "帘子一拉，外面是商场",
    category: "public",
    desc: "服装店试衣间。帘子、镜子、挂钩上的衣服。",
    color: "#f4a261",
    stages: [
      {
        name: "挑选",
        intensity: "warm",
        intro: "你挑了一件「给{other}看」的衣服。",
        rounds: [
          { kind: "roleplay", text: "【挑选】{self}导购，{other}顾客。进帘内帮试穿——手比衣服更先碰到皮肤。" },
          { kind: "dare", text: "只换上衣，出来给{other}看，看满意了亲一下再换下一套。" },
          { kind: "whisper", text: "说{other}穿哪件最让你想当场脱掉。" },
          { kind: "confess", text: "承认陪{other}逛街时想过在试衣间动手吗。" },
        ],
      },
      {
        name: "帘内",
        intensity: "hot",
        intro: "帘子拉到脚踝。外面脚步和音乐。",
        rounds: [
          { kind: "roleplay", text: "【帘内】两人挤进同一间，背贴镜子，前面贴彼此，手在下面忙。" },
          { kind: "dare", text: "咬{other}肩忍声，手指进去，外面有人问「好了吗」——答「快了」。" },
          { kind: "whisper", text: "描述帘子外世界和帘内欲望对比。" },
          { kind: "dare", text: "口舌快速伺候，听见导购脚步就停。" },
        ],
      },
      {
        name: "镜子",
        intensity: "hot",
        intro: "试衣镜从脚到头。新内衣挂在钩上。",
        rounds: [
          { kind: "roleplay", text: "【镜子】让{other}只穿新内衣对镜，你从后抱，镜子里看全身。" },
          { kind: "dare", text: "拉下肩带，嘴唇跟着肩带轨迹吻下去。" },
          { kind: "whisper", text: "说买下这件的真正原因——你想怎么撕/脱它。" },
          { kind: "roleplay", text: "【结账】穿好外套里面真空，牵手去收银台，捏手暗示回家。" },
        ],
      },
      {
        name: "回家拆",
        intensity: "deep",
        intro: "衣服买了。真正拆封在家。",
        rounds: [
          { kind: "dare", text: "用刚买的那件当道具——穿着做或撕着做，你选。" },
          { kind: "roleplay", text: "【回家拆】门口就吻，购物袋扔地上，衣服晚点再拆。" },
          { kind: "confess", text: "说出你还想和{other}在哪种店面试衣间冒险。" },
          { kind: "dare", text: "做到高潮，新衣服的吊牌还在地上。" },
        ],
      },
    ],
  },

  train_sleeper: {
    id: "train_sleeper",
    name: "火车卧铺",
    icon: "🚂",
    tagline: "夜色铁轨，摇晃的床",
    category: "vehicle",
    desc: "夜班火车软卧。轨道声、小桌板、帘子。",
    color: "#3d405b",
    stages: [
      {
        name: "铺位",
        intensity: "warm",
        intro: "下铺或中铺。列车晃，身体自然贴。",
        rounds: [
          { kind: "roleplay", text: "【铺位】列车晃，顺势倒进{other}怀里，手放在腰上装睡。" },
          { kind: "dare", text: "帘子拉上，在狭窄铺位深吻，列车过弯时加重。" },
          { kind: "whisper", text: "在轨道声里说想去哪座城市——以及路上想对{other}做什么。" },
          { kind: "confess", text: "说交通工具上最暧昧的一次回忆。" },
        ],
      },
      {
        name: "夜灯",
        intensity: "hot",
        intro: "过道夜灯微亮。对面铺位有人吗？不管了。",
        rounds: [
          { kind: "roleplay", text: "【夜灯】{other}躺，你侧躺面对面，手伸进睡衣下摆。" },
          { kind: "dare", text: "用被子盖住下半身，口舌或手指伺候，有人走过就停。" },
          { kind: "whisper", text: "描述列车摇晃像某种节奏。" },
          { kind: "dare", text: "忍声到{other}咬你肩膀留印。" },
        ],
      },
      {
        name: "过道",
        intensity: "hot",
        intro: "凌晨过道空无一人。车窗黑。",
        rounds: [
          { kind: "roleplay", text: "【过道】拉{other}到车厢连接处，冷风一激，吻更烫。" },
          { kind: "dare", text: "在洗手间快速弄彼此一次，回去装睡。" },
          { kind: "whisper", text: "说下一站之前要完成什么。" },
          { kind: "roleplay", text: "【乘务员】假装乘务员查票——交吻当票。" },
        ],
      },
      {
        name: "到站",
        intensity: "deep",
        intro: "广播报站。黎明。身体比目的地更早到达。",
        rounds: [
          { kind: "dare", text: "铺位上侧入或相拥进入，跟着列车节奏顶弄。" },
          { kind: "roleplay", text: "【到站】匆忙洗漱下车，行李箱里藏着昨晚乱掉的内衣。" },
          { kind: "confess", text: "约定下次长途旅行：火车还是飞机更色。" },
          { kind: "whisper", text: "到酒店第一分钟计划。" },
        ],
      },
    ],
  },

  rooftop: {
    id: "rooftop",
    name: "天台夜色",
    icon: "🌃",
    tagline: "城市在脚下，欲望在头顶",
    category: "outdoor",
    desc: "公寓或酒店天台。风大，灯火万千。",
    color: "#4895ef",
    stages: [
      {
        name: "上风",
        intensity: "warm",
        intro: "推开天台门。风灌进衣服。",
        rounds: [
          { kind: "roleplay", text: "【上风】从背后抱住{other}挡风，下巴搁肩，手从外套探进去。" },
          { kind: "dare", text: "在栏杆前接吻，城市在脚下，像向世界宣战。" },
          { kind: "whisper", text: "说风多大都要听清的一句想要。" },
          { kind: "confess", text: "承认高处让你更想{other}吗。" },
        ],
      },
      {
        name: "星空",
        intensity: "warm",
        intro: "找一块干净地面或躺椅。星星很少，但够浪漫。",
        rounds: [
          { kind: "roleplay", text: "【星空】并排挤在躺椅/地面，指星星，指到第三颗就亲一下。" },
          { kind: "dare", text: "外套铺地，{other}躺，你俯身隔衣摸到硬/湿。" },
          { kind: "whisper", text: "描述城市噪音里{other}喘息多清晰。" },
          { kind: "roleplay", text: "【偷渡】假装天台禁止入内——你们偏要，刺激加倍。" },
        ],
      },
      {
        name: "栏杆",
        intensity: "hot",
        intro: "栏杆冰凉。身体滚烫。",
        rounds: [
          { kind: "roleplay", text: "【栏杆】{other}扶栏杆翘臀，风掀起衣摆，你从后亲腰到腿根。" },
          { kind: "dare", text: "手指或口舌在栏杆边伺候，看城市灯火模糊。" },
          { kind: "whisper", text: "说在这里做若被远处看见，你也不停。" },
          { kind: "dare", text: "脱一件，风碰到皮肤，立刻用身体暖回去。" },
        ],
      },
      {
        name: "日出前",
        intensity: "deep",
        intro: "天边泛白。最后一夜要狠。",
        rounds: [
          { kind: "dare", text: "天台角落站立进入，风灌进衣服，抱紧{other}深顶。" },
          { kind: "roleplay", text: "【日出前】做到高潮，天边一线光打在脸上。" },
          { kind: "confess", text: "说出你想和{other}在哪个城市天台再来。" },
          { kind: "whisper", text: "下楼后电梯里不许说话，手却要牵着。" },
        ],
      },
    ],
  },

  hot_spring: {
    id: "hot_spring",
    name: "私汤温泉",
    icon: "♨️",
    tagline: "热气腾腾，肌肤赤裸",
    category: "outdoor",
    desc: "包场私汤或山间露天风吕。蒸汽、石头、竹声。",
    color: "#e76f51",
    stages: [
      {
        name: "入浴",
        intensity: "warm",
        intro: "先试水温。肩膀浸入。 sigh 一声。",
        rounds: [
          { kind: "roleplay", text: "【入浴】帮{other}拢头发，手指滑过后颈入水，水面下碰小腿。" },
          { kind: "dare", text: "面对面坐，水下腿缠腿，脚尖蹭到最敏感处。" },
          { kind: "whisper", text: "说蒸汽里{other}皮肤像什么（瓷器、蜜桃…要色）。" },
          { kind: "confess", text: "承认裸体泡汤看{other}身体的想法。" },
        ],
      },
      {
        name: "蒸汽",
        intensity: "warm",
        intro: "蒸汽浓得看不清对面表情，触觉更敏锐。",
        rounds: [
          { kind: "roleplay", text: "【蒸汽】蒙眼（蒸汽如蒙眼），水下摸索{other}身体，猜部位亲一下。" },
          { kind: "dare", text: "坐在池边石上，脚浸水里，{other}在水下口舌伺候。" },
          { kind: "whisper", text: "描述热水让你多想让{other}更烫。" },
          { kind: "roleplay", text: "【搓背】认真搓背，搓到腰以下手就不回来了。" },
        ],
      },
      {
        name: "露天",
        intensity: "hot",
        intro: "露天风吕。星空或竹墙。",
        rounds: [
          { kind: "roleplay", text: "【露天】{other}靠池边，你从后环抱，水下硬/湿贴着{other}臀缝。" },
          { kind: "dare", text: "水下手指进入，水波荡漾，保持表情平静。" },
          { kind: "whisper", text: "说竹叶沙沙像在为你们打拍子。" },
          { kind: "dare", text: "出池短暂在石头上口舌，再快速入水。" },
        ],
      },
      {
        name: "休息处",
        intensity: "deep",
        intro: "汤屋休息区。榻榻米、麦茶。身体还热。",
        rounds: [
          { kind: "roleplay", text: "【休息处】榻榻米上只围浴巾，从背后进入或相拥磨蹭到浴巾散开。" },
          { kind: "dare", text: "做到两人像刚从水里捞出来——汗与水混在一起。" },
          { kind: "confess", text: "约定下次私汤还是公共（角色扮演）。" },
          { kind: "whisper", text: "说回房间还要再来一轮干的。" },
        ],
      },
    ],
  },

  kitchen: {
    id: "kitchen",
    name: "午夜厨房",
    icon: "🍳",
    tagline: "冰箱光、料理台、围裙",
    category: "indoor",
    desc: "半夜饿的不只是胃。冰箱灯、料理台高度、围裙带子。",
    color: "#f94144",
    stages: [
      {
        name: "加餐",
        intensity: "warm",
        intro: "打开冰箱。冷光照脸。",
        rounds: [
          { kind: "roleplay", text: "【加餐】从背后抱{other}找吃的，手比食物更先找到腰。" },
          { kind: "dare", text: "喂{other}草莓/奶油，掉身上就舔，不许用手擦。" },
          { kind: "whisper", text: "说{other}穿着睡衣/围裙的样子多像一道菜。" },
          { kind: "confess", text: "承认厨房台面高度让你想过把{other}放上去吗。" },
        ],
      },
      {
        name: "料理台",
        intensity: "hot",
        intro: "台面冰凉。大腿贴上去一激灵。",
        rounds: [
          { kind: "roleplay", text: "【料理台】让{other}坐台面，你站两腿间，吻到{other}仰头。" },
          { kind: "dare", text: "奶油/蜂蜜涂{other}胸口或小腹，舔干净。" },
          { kind: "whisper", text: "描述{other}在台面上的腿缠你腰的样子。" },
          { kind: "dare", text: "台面边口舌伺候，盘子碰落也不停。" },
        ],
      },
      {
        name: "围裙",
        intensity: "hot",
        intro: "只穿围裙。背后真空。",
        rounds: [
          { kind: "roleplay", text: "【围裙】{other}只穿围裙，你从后解带子，嘴唇跟带子一起滑下去。" },
          { kind: "dare", text: "围裙掀起，从后进入或紧贴磨蹭，镜子里看围裙晃。" },
          { kind: "whisper", text: "说围裙比裸体更色，因为随时可掀开。" },
          { kind: "roleplay", text: "【早餐】假装做早餐，实际在料理台边做{other}。" },
        ],
      },
      {
        name: "洗碗",
        intensity: "deep",
        intro: "事后总要收拾。但可以边洗边继续。",
        rounds: [
          { kind: "dare", text: "{other}洗碗，你从后顶入或磨蹭，水龙头发烫。" },
          { kind: "roleplay", text: "【洗碗】洗一个碗亲一下，洗慢了惩罚是更深的一下。" },
          { kind: "confess", text: "说出你想在厨房对{other}做的最色早餐。" },
          { kind: "dare", text: "做到高潮，明早真的做早餐当奖励。" },
        ],
      },
    ],
  },

  ktv: {
    id: "ktv",
    name: "KTV包房",
    icon: "🎤",
    tagline: "麦克风关，欲望开",
    category: "indoor",
    desc: "隔音包房。屏幕光影、沙发、低糖啤酒。",
    color: "#ff006e",
    stages: [
      {
        name: "点歌",
        intensity: "warm",
        intro: "话筒递给{other}。你坐得比朋友近。",
        rounds: [
          { kind: "roleplay", text: "【点歌】合唱一首情歌，每句尾音落在一个吻上。" },
          { kind: "dare", text: "关原唱，只留伴奏，边唱边手伸进{other}衣摆。" },
          { kind: "whisper", text: "说{other}唱歌时喉结/嘴唇多让你想堵上。" },
          { kind: "confess", text: "承认KTV里想过{other}吗。" },
        ],
      },
      {
        name: "沙发",
        intensity: "hot",
        intro: "沙发深。屏幕光忽明忽暗。",
        rounds: [
          { kind: "roleplay", text: "【沙发】{other}半躺，你跪沙发边口舌，麦克风扔一边。" },
          { kind: "dare", text: "隔着牛仔裤/裙磨蹭到{other}抓沙发皮。" },
          { kind: "whisper", text: "描述屏幕MV里谁在演，你们在做什么。" },
          { kind: "dare", text: "让{other}捂麦忍声，你弄两分钟。" },
        ],
      },
      {
        name: "立麦",
        intensity: "hot",
        intro: "站着唱。站着做。",
        rounds: [
          { kind: "roleplay", text: "【立麦】{other}扶立麦，你从后贴上来，手从裤腰探入，歌不能停。" },
          { kind: "dare", text: "关掉屏幕灯，只剩氛围灯，在沙发上脱到一半。" },
          { kind: "whisper", text: "说隔音有多好，{other}可以叫多大声。" },
          { kind: "roleplay", text: "【合唱】对唱变成喘息二重奏。" },
        ],
      },
      {
        name: "散场",
        intensity: "deep",
        intro: "时间到。服务员敲门。最后一首。",
        rounds: [
          { kind: "dare", text: "服务员敲门前三分钟快速弄到高潮，整理包厢开门说「马上好」。" },
          { kind: "roleplay", text: "【散场】牵手出包厢，眼神正常，手在暗处捏{other}。" },
          { kind: "confess", text: "约定下次包房点几首歌当暗号。" },
          { kind: "whisper", text: "回家路上复述包房里最爽的一刻。" },
        ],
      },
    ],
  },

  pool_night: {
    id: "pool_night",
    name: "泳池之夜",
    icon: "🏊",
    tagline: "水波、月光、救生员下班",
    category: "outdoor",
    desc: "酒店或别墅泳池。夜里无人，水声掩盖一切。",
    color: "#00b4d8",
    stages: [
      {
        name: "池边",
        intensity: "warm",
        intro: "水纹映月光。脚趾试水。",
        rounds: [
          { kind: "roleplay", text: "【池边】拉{other}坐池边脚浸水，从膝吻到大腿，水珠往下淌。" },
          { kind: "dare", text: "只穿泳装互脱肩带，跳进水里再浮上来吻。" },
          { kind: "whisper", text: "说{other}湿发贴脸的样子。" },
          { kind: "confess", text: "承认泳池边看过{other}身材。" },
        ],
      },
      {
        name: "水中",
        intensity: "hot",
        intro: "水浮力。身体更轻，接触更滑。",
        rounds: [
          { kind: "roleplay", text: "【水中】面对面抱，腿缠腰，水下手探进泳裤。" },
          { kind: "dare", text: "池壁边让{other}扶砖，你从后亲颈到背，水下手指进去。" },
          { kind: "whisper", text: "描述水的阻力让动作更慢更磨人。" },
          { kind: "dare", text: "水下口舌憋气伺候，浮上来换气再下去。" },
        ],
      },
      {
        name: "躺椅",
        intensity: "hot",
        intro: "出水。皮肤滴水。躺椅还温。",
        rounds: [
          { kind: "roleplay", text: "【躺椅】{other}趴躺椅，你从后涂防晒油——油滑到腿根。" },
          { kind: "dare", text: "躺椅上做口舌或进入，水从发梢滴下。" },
          { kind: "whisper", text: "说月光下{other}皮肤油光多色。" },
          { kind: "roleplay", text: "【救生员】假装救生员巡逻——躲阴影里继续。" },
        ],
      },
      {
        name: "浸夜",
        intensity: "deep",
        intro: "泳池闭馆时间过了。只属于你们的水面。",
        rounds: [
          { kind: "dare", text: "池边或浅水区进入，水浪拍池壁。" },
          { kind: "roleplay", text: "【浸夜】抱回房间不擦干，在床上水渍里继续。" },
          { kind: "confess", text: "说出你想和{other}在哪片水域再来。" },
          { kind: "dare", text: "高潮后真的回池里游一圈，像庆祝。" },
        ],
      },
    ],
  },

  camping_tent: {
    id: "camping_tent",
    name: "野外帐篷",
    icon: "⛺",
    tagline: "虫鸣、睡袋、只有一层布",
    category: "outdoor",
    desc: "森林或海边营地。帐篷薄，外面是星空和虫鸣。",
    color: "#588157",
    stages: [
      {
        name: "生火",
        intensity: "warm",
        intro: "篝火噼啪。帐篷还没进。",
        rounds: [
          { kind: "roleplay", text: "【生火】烤棉花糖喂{other}，糖浆沾唇舔掉，再吻。" },
          { kind: "dare", text: "篝火光里脱外套，只留一层，互相看轮廓。" },
          { kind: "whisper", text: "说野外没有墙，只有帐篷，让你多大胆。" },
          { kind: "confess", text: "承认露营时想过{other}吗。" },
        ],
      },
      {
        name: "睡袋",
        intensity: "warm",
        intro: "拉链拉上。空间只够缠在一起。",
        rounds: [
          { kind: "roleplay", text: "【睡袋】共用睡袋，拉链拉到下巴，手在下面互相摸索。" },
          { kind: "dare", text: "在睡袋里脱到赤裸，皮肤贴皮肤取暖。" },
          { kind: "whisper", text: "虫鸣里描述{other}体温。" },
          { kind: "roleplay", text: "【外面】帐篷布上映出两人影子——故意动给星空看。" },
        ],
      },
      {
        name: "夜巡",
        intensity: "hot",
        intro: "借口小解出帐篷。其实想在外面吻。",
        rounds: [
          { kind: "roleplay", text: "【夜巡】树影下深吻，手伸进裤子，远处车灯一扫就停。" },
          { kind: "dare", text: "帐篷口跪着口交，帐帘只拉一半。" },
          { kind: "whisper", text: "说森林/海边夜里气味让你上头。" },
          { kind: "dare", text: "回帐篷前在草地上躺一分钟互相摸。" },
        ],
      },
      {
        name: "黎明",
        intensity: "deep",
        intro: "鸟鸣。帐篷里闷热。",
        rounds: [
          { kind: "dare", text: "睡袋里侧入或相拥进入，跟着外面鸟叫节奏。" },
          { kind: "roleplay", text: "【黎明】拉链拉开透气，晨光打在交缠身体上。" },
          { kind: "confess", text: "约定下次露营带什么「增加情趣」。" },
          { kind: "whisper", text: "说回家也要买睡袋——为了重温。" },
        ],
      },
    ],
  },

  balcony: {
    id: "balcony",
    name: "阳台夏夜",
    icon: "🌙",
    tagline: "对面有窗，你们也有",
    category: "outdoor",
    desc: "公寓阳台。夏夜有风，对面楼亮着灯。",
    color: "#cdb4db",
    stages: [
      {
        name: "乘凉",
        intensity: "warm",
        intro: "搬两把椅子。冰啤酒。睡衣。",
        rounds: [
          { kind: "roleplay", text: "【乘凉】{other}坐，你站背后按摩肩，越按越低。" },
          { kind: "dare", text: "对面楼有人窗开——故意吻{other}给陌生人看剪影。" },
          { kind: "whisper", text: "说对面若看见，你会更兴奋还是更收敛。" },
          { kind: "confess", text: "承认阳台暴露感让你想过{other}。" },
        ],
      },
      {
        name: "夜风",
        intensity: "hot",
        intro: "风掀起睡衣下摆。不拉。",
        rounds: [
          { kind: "roleplay", text: "【夜风】让{other}扶栏杆，你从后掀起衣摆亲臀与腰。" },
          { kind: "dare", text: "手伸进{other}睡裤，风碰到裸露皮肤。" },
          { kind: "whisper", text: "描述城市远处车灯像见证。" },
          { kind: "dare", text: "跪下口交，栏杆外是夜空。" },
        ],
      },
      {
        name: "窗帘",
        intensity: "hot",
        intro: "退回屋内。窗帘没拉严。",
        rounds: [
          { kind: "roleplay", text: "【窗帘】半拉窗帘继续在阳台边做，外面能窥见一角。" },
          { kind: "dare", text: "进屋内落地窗前对着玻璃做，像展览。" },
          { kind: "whisper", text: "说玻璃上雾气是{other}的呼吸。" },
          { kind: "roleplay", text: "【邻居】假装邻居亮灯——刺激停三秒再继续。" },
        ],
      },
      {
        name: "夏夜尽",
        intensity: "deep",
        intro: "夜深。虫鸣。该进屋了。",
        rounds: [
          { kind: "dare", text: "阳台躺椅或进屋沙发，进入做到高潮。" },
          { kind: "roleplay", text: "【夏夜尽】抱进卧室，阳台门不关，风跟着进来。" },
          { kind: "confess", text: "说出你想在哪个季节、哪个阳台再来。" },
          { kind: "whisper", text: "约定明早阳台吃早餐——穿多少你定。" },
        ],
      },
    ],
  },

  storage_closet: {
    id: "storage_closet",
    name: "储藏室",
    icon: "📦",
    tagline: "杂物堆里的秘密",
    category: "indoor",
    desc: "公司或家里的储物间。窄、闷、门一锁就是世界尽头。",
    color: "#6c757d",
    stages: [
      {
        name: "躲进来",
        intensity: "warm",
        intro: "借口找东西把{other}拉进来。门锁咔哒。",
        rounds: [
          { kind: "roleplay", text: "【躲进来】杂物架之间接吻，纸箱碰落，不管。" },
          { kind: "dare", text: "三十秒内在黑暗里摸清{other}三件衣物位置。" },
          { kind: "whisper", text: "在闷热空气里说有多想要。" },
          { kind: "confess", text: "承认狭窄空间让你更兴奋吗。" },
        ],
      },
      {
        name: "黑暗",
        intensity: "hot",
        intro: "没灯。只有门缝一线光。",
        rounds: [
          { kind: "roleplay", text: "【黑暗】背靠门，{other}面对你，手在下面忙，外面脚步经过就停。" },
          { kind: "dare", text: "跪地口交，门缝光打在{other}侧脸。" },
          { kind: "whisper", text: "描述黑暗中{other}呼吸打在颈上。" },
          { kind: "dare", text: "手指弄到{other}咬你肩不出声。" },
        ],
      },
      {
        name: "杂物",
        intensity: "hot",
        intro: "毯子、旧衣服——临时铺在地上。",
        rounds: [
          { kind: "roleplay", text: "【杂物】铺毯子，{other}躺，你俯身，头顶碰架子的闷响。" },
          { kind: "dare", text: "用领带/丝巾轻缚{other}手腕（可解），口头命令三个动作。" },
          { kind: "whisper", text: "说这种偷来的空间像偷来的时间。" },
          { kind: "roleplay", text: "【敲门】外面有人找——屏息三秒，人走远爆发吻。" },
        ],
      },
      {
        name: "出来",
        intensity: "deep",
        intro: "要出去了。衣衫要整齐。欲望要安放或带走。",
        rounds: [
          { kind: "dare", text: "站立快速深顶二十下，整理衣冠开门若无其事。" },
          { kind: "roleplay", text: "【出来】各抱一箱杂物当掩护，眼神交换。" },
          { kind: "confess", text: "说出你还想在哪类「杂物间」再来。" },
          { kind: "whisper", text: "约定回家补完，门一关就执行。" },
        ],
      },
    ],
  },

  supermarket: {
    id: "supermarket",
    name: "超市货架",
    icon: "🛒",
    tagline: "购物车挡住的不只是视线",
    category: "public",
    desc: "深夜或周末的超市。货架高耸，冷柜嗡鸣，转角无人——购物车成了移动屏障。",
    color: "#95d5b2",
    stages: [
      {
        name: "采购",
        intensity: "warm",
        intro: "推着购物车「认真采购」，手却在推车把手下交缠。",
        rounds: [
          { kind: "roleplay", text: "【采购】在零食货架前，{self}踮脚够高处，{other}从身后贴上来「帮忙」，手却放在腰上。" },
          { kind: "dare", text: "冷藏柜前假装比价，实际在玻璃倒影里接吻三秒。" },
          { kind: "whisper", text: "告诉{other}：你最想用超市哪样「商品」逗{other}。" },
          { kind: "confess", text: "承认有没有在超市人多时偷看过{other}的腿/臀。" },
        ],
      },
      {
        name: "转角",
        intensity: "hot",
        intro: "日用品区转角，监控死角。购物车横在过道中间。",
        rounds: [
          { kind: "roleplay", text: "【转角】把{other}抵在货架，膝盖顶开腿，外面有人推车经过立刻分开装看商品。" },
          { kind: "dare", text: "手伸进{other}外套里摸三十秒，听见广播促销才停。" },
          { kind: "whisper", text: "描述等下结账后车里你想怎么继续。" },
          { kind: "dare", text: "各往对方口袋塞一件「违禁」小物（如巧克力/安全套），结账时眼神交换。" },
        ],
      },
      {
        name: "试吃",
        intensity: "hot",
        intro: "促销台试吃，勺子共用。甜味在舌尖，欲望在桌下。",
        rounds: [
          { kind: "roleplay", text: "【试吃】喂{other}一口，舔掉{other}唇角残渣，促销员看过来就正经点头说「好吃」。" },
          { kind: "dare", text: "在停车场手推车旁深吻，购物袋落地也不管，一分钟。" },
          { kind: "whisper", text: "用试吃品的口感比喻{other}身体某处。" },
          { kind: "roleplay", text: "【推车】坐进购物车（或扶车沿），{other}推你穿过空荡货架区，你仰头索吻。" },
        ],
      },
      {
        name: "车尾",
        intensity: "deep",
        intro: "地下停车场车尾箱。购物袋堆在一边，世界剩下一小块铁皮内的空间。",
        rounds: [
          { kind: "dare", text: "车尾箱半开，{other}坐沿你站着，快速手口伺候到{other}抓紧箱盖。" },
          { kind: "roleplay", text: "【车尾】钻进后座，购物袋当枕头，省略前戏直接纠缠。" },
          { kind: "confess", text: "说出这种「日常里偷情」是否更刺激。" },
          { kind: "whisper", text: "约定：袋子里某样东西回家当「道具」用。" },
        ],
      },
    ],
  },

  ferris_wheel: {
    id: "ferris_wheel",
    name: "摩天轮",
    icon: "🎡",
    tagline: "升到最高处才敢做的事",
    category: "outdoor",
    desc: "游乐园夜场。轿厢升到顶点停住的几秒，城市在脚下，只有你们。",
    color: "#ffafcc",
    stages: [
      {
        name: "排队",
        intensity: "warm",
        intro: "队伍缓慢前移。彩灯闪烁，{other}的手已经不老实地勾着你。",
        rounds: [
          { kind: "roleplay", text: "【排队】假装第一次约会，牵{other}手问「怕不怕高」，拇指在掌心画圈。" },
          { kind: "dare", text: "在人群里从背后抱{other}，嘴唇蹭{other}耳廓，被回头看就松开。" },
          { kind: "whisper", text: "告诉{other}顶点停住时你第一件想做的事。" },
          { kind: "confess", text: "承认你想在「半空」对{other}做什么。" },
        ],
      },
      {
        name: "上升",
        intensity: "warm",
        intro: "轿厢门关上。地面越来越远。安全带是唯一的规矩。",
        rounds: [
          { kind: "roleplay", text: "【上升】膝并膝，手在毯子下互摸大腿，看窗外装镇定。" },
          { kind: "dare", text: "解开{other}外套一颗扣，亲锁骨，下一格轿厢升到视线平齐就扣好。" },
          { kind: "whisper", text: "描述城市灯火像什么，而{other}比灯火更烫。" },
          { kind: "dare", text: "轮流闭眼，用手猜对方隔衣摸的是哪一处。" },
        ],
      },
      {
        name: "顶点",
        intensity: "hot",
        intro: "轿厢在最高点停住。全世界安静三秒——或更久。",
        rounds: [
          { kind: "roleplay", text: "【顶点】停住瞬间深吻，手探进衣内，下去前整理好衣冠。" },
          { kind: "dare", text: "{other}坐你腿上面对面，毯子盖住下半身，动三十秒轿厢即动则停。" },
          { kind: "whisper", text: "在最高处说最想和{other}做的露骨一句。" },
          { kind: "roleplay", text: "【俯瞰】指着远处某栋楼：「下次去那里，换张床。」现在先用手兑现一部分。" },
        ],
      },
      {
        name: "降落",
        intensity: "deep",
        intro: "落地前最后一圈。欲望来不及等回家。",
        rounds: [
          { kind: "dare", text: "最后一停时，口舌或手指让{other}咬唇忍住声音。" },
          { kind: "roleplay", text: "【降落】门开前整理头发，牵手下车像什么都没发生——眼神出卖你们。" },
          { kind: "confess", text: "说出顶点时你真实的心跳是怕高还是想要。" },
          { kind: "whisper", text: "约定游乐园闭园前去哪「续摊」。" },
        ],
      },
    ],
  },

  backstage: {
    id: "backstage",
    name: "后台化妆间",
    icon: "💄",
    tagline: "幕布落下，戏才刚开始",
    category: "indoor",
    desc: "演出或拍摄结束后的后台。镜灯还亮着，戏服半脱，角色与真人重叠。",
    color: "#e9c46a",
    stages: [
      {
        name: "卸妆",
        intensity: "warm",
        intro: "镜前卸妆。化妆棉划过皮肤，像一层角色被慢慢擦掉。",
        rounds: [
          { kind: "roleplay", text: "【卸妆】{self}帮{other}卸眼妆，凑很近，鼻尖碰鼻尖：「戏演完了，现在是谁？」" },
          { kind: "dare", text: "用卸妆棉蘸水在{other}锁骨写一个字，舔掉。" },
          { kind: "whisper", text: "告诉{other}台上哪个瞬间你最想冲下去吻{other}。" },
          { kind: "confess", text: "承认你有没有幻想过{other}的戏服/制服。" },
        ],
      },
      {
        name: "戏服",
        intensity: "hot",
        intro: "戏服拉链、别针、腰带——一件件解开像拆礼物。",
        rounds: [
          { kind: "roleplay", text: "【戏服】继续演一分钟：{other}是明星，{self}是助理「违规」帮脱衣。" },
          { kind: "dare", text: "只脱到内衣/内裤，在镜前摆最后一个舞台造型，你从背后伸手进去。" },
          { kind: "whisper", text: "用角色口吻命令{other}做一件事，然后撕掉角色壳：「现在，照做。」" },
          { kind: "dare", text: "坐在化妆台边，腿架你肩上，口红当道具在腿内侧画线再吻掉。" },
        ],
      },
      {
        name: "镜灯",
        intensity: "hot",
        intro: "一圈镜灯全亮。无处可藏，每一寸皮肤都被看见。",
        rounds: [
          { kind: "roleplay", text: "【镜灯】{other}面对镜子，你从后环抱，手探下去，让{other}看自己表情。" },
          { kind: "dare", text: "跪在两腿间口交，镜子里对视，不许闭眼。" },
          { kind: "whisper", text: "描述镜中{other}什么样子让你最想弄哭/弄软。" },
          { kind: "roleplay", text: "【补妆】高潮后拿口红在{other}身上「签名」，再帮{other}补唇妆出门。" },
        ],
      },
      {
        name: "庆功",
        intensity: "deep",
        intro: "门外队友在庆功。门内你们用身体庆功。",
        rounds: [
          { kind: "dare", text: "化妆台上做，手捂嘴，门外脚步声经过就停。" },
          { kind: "roleplay", text: "【庆功】抱{other}坐沙发，缓慢进入，每一下说一个今晚值得纪念的细节。" },
          { kind: "confess", text: "说出你想和{other}演哪一种「戏中戏」。" },
          { kind: "whisper", text: "约定庆功宴上桌下的小动作。" },
        ],
      },
    ],
  },

  parking_garage: {
    id: "parking_garage",
    name: "地下停车场",
    icon: "🅿️",
    tagline: "混凝土回声里的秘密",
    category: "public",
    desc: "商场或写字楼的地下层。荧光灯嗡鸣，柱子投影，引擎声远——近处只有你们。",
    color: "#adb5bd",
    stages: [
      {
        name: "找车",
        intensity: "warm",
        intro: "假装找不到车，在 B2 层绕圈。其实知道在哪，只想多走一会儿。",
        rounds: [
          { kind: "roleplay", text: "【找车】柱子阴影里接吻，远处车灯扫过就分开继续走。" },
          { kind: "dare", text: "按响车锁，灯闪瞬间把{other}拉进怀里深吻。" },
          { kind: "whisper", text: "告诉{other}：这种空旷阴冷的地方为何让你想靠近{other}。" },
          { kind: "confess", text: "承认有没有在停车场等{other}时想过车震。" },
        ],
      },
      {
        name: "后座",
        intensity: "hot",
        intro: "车门锁上。车窗起雾。外面偶尔有车驶过。",
        rounds: [
          { kind: "roleplay", text: "【后座】{other}躺，你俯身，顶太低就换侧躺纠缠。" },
          { kind: "dare", text: "后窗雾了，用手指画心再擦掉，手伸进{other}衣服。" },
          { kind: "whisper", text: "描述{other}在后座狭窄空间里的味道与体温。" },
          { kind: "dare", text: "口舌伺候到{other}抓座椅，有人路过立刻装睡。" },
        ],
      },
      {
        name: "柱后",
        intensity: "hot",
        intro: "不上车。柱子后面，混凝土吸走一部分声音。",
        rounds: [
          { kind: "roleplay", text: "【柱后】{other}背靠柱，你膝盖顶腿间，手在下面忙，电梯门开就停。" },
          { kind: "dare", text: "掀起/拉开衣物，快速弄湿/弄硬，三十秒内{other}不许出声。" },
          { kind: "whisper", text: "说如果监控就在柱顶，你仍会做哪一步。" },
          { kind: "roleplay", text: "【回声】故意压低呻吟，听混凝土回声，再吻住{other}把声音吃掉。" },
        ],
      },
      {
        name: "驶离",
        intensity: "deep",
        intro: "坡道向上。出口天光刺眼。欲望要在驶离前或之后安放。",
        rounds: [
          { kind: "dare", text: "驾驶座/副驾，手伸进裤腰互相弄到呼吸乱，上坡前停手。" },
          { kind: "roleplay", text: "【驶离】出闸口对视一笑，手在档把下交缠。" },
          { kind: "confess", text: "说出最刺激的一次「差点被发现」回忆。" },
          { kind: "whisper", text: "约定到家电梯里继续，或路边找店买一样东西当今晚道具。" },
        ],
      },
    ],
  },

  sauna_room: {
    id: "sauna_room",
    name: "桑拿房",
    icon: "♨️",
    tagline: "热气把防备蒸光",
    category: "indoor",
    desc: "会所或酒店的桑拿/蒸汽房。木板、热气、毛巾——皮肤滑腻，界限模糊。",
    color: "#e76f51",
    stages: [
      {
        name: "进房",
        intensity: "warm",
        intro: "热气扑面。毛巾围腰。坐下时膝盖必然相碰。",
        rounds: [
          { kind: "roleplay", text: "【进房】递毛巾给{other}，指尖蹭过手背，像陌生人在会所偶遇。" },
          { kind: "dare", text: "靠{other}肩闭眼，手放在{other}大腿上，计时两分钟不解释。" },
          { kind: "whisper", text: "在热气里告诉{other}：汗湿的{other}哪里最好看。" },
          { kind: "confess", text: "承认高温是否让你更想要{other}。" },
        ],
      },
      {
        name: "蒸腾",
        intensity: "hot",
        intro: "水泼在石上，白雾涌起。看不清脸，触觉被放大。",
        rounds: [
          { kind: "roleplay", text: "【蒸腾】雾中摸索对方，吻到喉结/锁骨才认清是谁。" },
          { kind: "dare", text: "毛巾滑落不许捡，互相看十秒再帮围好——手故意多停留。" },
          { kind: "whisper", text: "描述雾中{other}的喘息像什么。" },
          { kind: "dare", text: "跪姿帮{other}冲水，水流滑过皮肤，手跟着水流走。" },
        ],
      },
      {
        name: "木板",
        intensity: "hot",
        intro: "躺下。木板烫背，皮肤却更烫。",
        rounds: [
          { kind: "roleplay", text: "【木板】{other}躺，你侧躺相贴，手伸进毛巾下探索。" },
          { kind: "dare", text: "口舌从胸滑到小腹，{other}咬住自己毛巾角不出声。" },
          { kind: "whisper", text: "说这种「合法裸露」让你多大胆。" },
          { kind: "roleplay", text: "【换班】轮流浇热水在对方身上，浇一处亲一处。" },
        ],
      },
      {
        name: "冲凉",
        intensity: "deep",
        intro: "出桑拿冲凉。冷水激一下，欲望却更清醒。",
        rounds: [
          { kind: "dare", text: "冲凉间隔间，冷水下快速深吻，手在下面弄到{other}腿软。" },
          { kind: "roleplay", text: "【冲凉】帮{other}打皂，全身滑腻，从背后进入或紧贴磨蹭。" },
          { kind: "confess", text: "说出你还想和{other}试哪种「热/冷」反差玩法。" },
          { kind: "whisper", text: "约定回房间第一件事，不许先擦干。" },
        ],
      },
    ],
  },

  yacht_deck: {
    id: "yacht_deck",
    name: "游艇甲板",
    icon: "⛵",
    tagline: "海平线尽头只有彼此",
    category: "outdoor",
    desc: "私人游艇或包船出海。甲板晒热，船身摇晃，海天一色——放纵有了借口。",
    color: "#48cae4",
    stages: [
      {
        name: "启航",
        intensity: "warm",
        intro: "缆绳解开，引擎低鸣。甲板风大，要靠在一起才稳。",
        rounds: [
          { kind: "roleplay", text: "【启航】{self}船长，{other}贵宾。扶{other}上甲板，手在腰上多停：「风浪大，抓紧我。」" },
          { kind: "dare", text: "船身一晃故意倒进{other}怀里，吻住平衡身体。" },
          { kind: "whisper", text: "指着海平线：今晚尽头只有我们，你想怎么过。" },
          { kind: "confess", text: "承认你有没有幻想过海上的{other}。" },
        ],
      },
      {
        name: "日光",
        intensity: "warm",
        intro: "甲板躺椅。防晒油、墨镜、比基尼/泳裤——皮肤油亮。",
        rounds: [
          { kind: "roleplay", text: "【日光】帮{other}涂防晒，从肩到腿根，越涂越慢，{other}翻身就涂背面。" },
          { kind: "dare", text: "解开比基尼系带/泳裤边缘，用毛巾盖住，问{other}敢不敢继续晒。" },
          { kind: "whisper", text: "描述油亮皮肤下你想咬哪里。" },
          { kind: "dare", text: "躺椅并排挤在一起，手伸进对方泳装里，船员脚步声来就停。" },
        ],
      },
      {
        name: "船舱",
        intensity: "hot",
        intro: "进舱避日。船身摇晃像永不停的前戏。",
        rounds: [
          { kind: "roleplay", text: "【船舱】狭窄卧铺，随浪起伏，进入时每一浪顶更深。" },
          { kind: "dare", text: "窗贴海色，{other}扶窗你从后，浪大时加力。" },
          { kind: "whisper", text: "边动边说：晕船还是晕{other}。" },
          { kind: "roleplay", text: "【船长室】坐驾驶椅，{other}跨坐你腿，假装开船实际失控。" },
        ],
      },
      {
        name: "月夜",
        intensity: "deep",
        intro: "锚泊海上。月光洒甲板。远处城市灯火像星屑。",
        rounds: [
          { kind: "dare", text: "甲板毯子上做，海风吹皮肤，互相盖住对方嘴忍住叫。" },
          { kind: "roleplay", text: "【月夜】裸体或半裸看海，从拥抱到进入，浪花拍船身打节拍。" },
          { kind: "confess", text: "说出你想和{other}去哪片海再来一次。" },
          { kind: "whisper", text: "返航前约定：上岸后第一件事。" },
        ],
      },
    ],
  },
});